name: GitHub Actions Build and Deploy

# 触发条件: push 到 main 分支后
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

# 设置权限
permissions: write-all

# 设置上海时区
env:
  TZ: Asia/Shanghai

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # 设置 node 版本
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 打包静态文件
      - name: Run Script
        env:
          APP_BASE_PATH: /maomao1996/subconverter-web
        run: pnpm install && pnpm run build

      - name: Copy files
        run: cp README.md ./dist/

      # 部署
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 静态文件所在目录
          folder: dist
